const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let leaders=[], penalties=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0)+' $';
function daysLeft(d){return Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000)}
function dayClass(d){return d<0?'danger':d<=3?'danger':d<=7?'warn':'ok'}
function typeClass(t){return t==='Строгий выговор'?'strict':t==='Выговор'?'reprimand':'warn'}
function fmtDate(d){if(!d)return '—';const [y,m,day]=d.split('-');return `${day}.${m}.${y}`}
async function api(url,opt){const r=await fetch(url,opt);if(!r.ok){let x={};try{x=await r.json()}catch{};throw new Error(x.error||'Ошибка запроса')}return r.json()}
async function load(){try{const [s,l,p]=await Promise.all([api('/api/stats'),api('/api/leaders'),api('/api/penalties')]);leaders=l;penalties=p;$('#sLeaders').textContent=s.leaders;$('#sActive').textContent=s.active;$('#sPenalties').textContent=s.penalties;const attention=leaders.filter(x=>x.status==='Активен'&&daysLeft(x.end_date)>=0&&daysLeft(x.end_date)<=7).length;$('#sAttention').textContent=attention;renderAll()}catch(e){console.error(e);}}
function renderAll(){renderLeaders();renderPenalties();renderSoon();renderCalendar();renderStructures();$('#leaderSelect').innerHTML=leaders.map(x=>`<option value="${x.id}">${esc(x.structure)} — ${esc(x.leader)}</option>`).join('')}
function renderLeaders(){const q=($('#leaderSearch')?.value||'').toLowerCase(),f=$('#statusFilter')?.value||'';const rows=leaders.filter(x=>(!q||(x.leader+' '+x.structure+' '+x.vk).toLowerCase().includes(q))&&(!f||x.status===f));$('#leadersTable').innerHTML=rows.length?rows.map(x=>{const d=daysLeft(x.end_date);return `<tr><td class="structure-cell">${esc(x.structure)}</td><td><b>${esc(x.leader)}</b></td><td>${esc(x.vk||'—')}</td><td>${fmtDate(x.start_date)} — ${fmtDate(x.end_date)}</td><td><span class="days ${dayClass(d)}">${d<0?'Срок истёк':d+' дн.'}</span></td><td><span class="status ${x.status==='Активен'?'active':'done'}">${esc(x.status)}</span></td><td><button class="table-action" onclick="removeLeader(${x.id})">Удалить</button></td></tr>`}).join(''):'<tr><td colspan="7" class="empty">По заданным условиям ничего не найдено</td></tr>'}
function renderSoon(){const a=[...leaders].filter(x=>x.status==='Активен'&&daysLeft(x.end_date)>=0).sort((a,b)=>a.end_date.localeCompare(b.end_date)).slice(0,6);$('#soon').innerHTML=a.length?a.map(x=>{const d=daysLeft(x.end_date);return `<div class="item"><div class="item-main"><div class="item-title">${esc(x.structure)} <span class="muted">· ${esc(x.leader)}</span></div><div class="muted">Срок до ${fmtDate(x.end_date)}</div></div><div class="days ${dayClass(d)}">${d} дн.</div></div>`}).join(''):'<div class="empty">Нет активных сроков</div>'}
function renderPenalties(){const q=($('#penaltySearch')?.value||'').toLowerCase(),f=$('#penaltyType')?.value||'';const rows=penalties.filter(x=>(!q||(x.reason+' '+x.leader+' '+x.structure).toLowerCase().includes(q))&&(!f||x.type===f));$('#penaltyTable').innerHTML=rows.length?rows.map(x=>`<tr><td>${fmtDate(x.date)}</td><td class="structure-cell">${esc(x.structure||'—')}</td><td>${esc(x.leader||'—')}</td><td><span class="type ${typeClass(x.type)}">${esc(x.type)}</span></td><td>${esc(x.reason)}</td><td class="money">${money(x.amount)}</td><td><button class="table-action" onclick="removePenalty(${x.id})">Удалить</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Взысканий пока нет</td></tr>';$('#recent').innerHTML=penalties.slice(0,5).map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.structure||'—')} · ${esc(x.leader||'—')}</div><div class="muted"><span class="type ${typeClass(x.type)}">${esc(x.type)}</span> · ${esc(x.reason)}</div></div><div class="money">${money(x.amount)}</div></div>`).join('')||'<div class="empty">Взысканий пока нет</div>'}
function renderStructures(){const map={};leaders.forEach(x=>{map[x.structure]??={active:0,total:0};map[x.structure].total++;if(x.status==='Активен')map[x.structure].active++});const a=Object.entries(map);$('#structureStats').innerHTML=a.length?a.map(([name,v])=>`<div class="structure-row"><div><div class="structure-name">${esc(name)}</div><div class="structure-meta">${v.total} назнач. · ${v.active} активн.</div></div><span class="badge ${v.active?'ok':''}">${v.active?'Активна':'Нет лидера'}</span></div>`).join(''):'<div class="empty">Структуры появятся после добавления лидеров</div>'}
function renderCalendar(){const a=[...leaders].sort((x,y)=>x.end_date.localeCompare(y.end_date));$('#calendarList').innerHTML=a.length?a.map(x=>{const d=daysLeft(x.end_date);const total=Math.max(1,Math.ceil((new Date(x.end_date)-new Date(x.start_date))/86400000));const passed=Math.min(total,Math.max(0,total-Math.max(0,d)));const pct=Math.round(passed/total*100);return `<div class="deadline"><div class="deadline-date">${fmtDate(x.end_date)}<small>окончание</small></div><div><b>${esc(x.structure)} · ${esc(x.leader)}</b><div class="muted">${esc(x.status)} · начало ${fmtDate(x.start_date)}</div><div class="progress"><i style="width:${pct}%"></i></div></div><div class="days ${dayClass(d)}">${d<0?'Истёк':d+' дн.'}</div></div>`}).join(''):'<div class="empty">Лидеров нет</div>'}
function show(id){$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden');const data={dashboard:['Центр управления','Контроль лидеров, сроков и дисциплины'],leaders:['Лидеры гражданских структур','Назначения, сроки и текущий статус'],penalties:['Дисциплинарные взыскания','Предупреждения, выговоры и их стоимость'],calendar:['Контроль сроков','Приоритет отсортирован по дате окончания']}[id];$('#title').textContent=data[0];$('#subtitle').textContent=data[1];$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav,[data-page]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));
function openModal(id){$(id).showModal()}function closeModal(id){$(id).close()}
$('#addLeader').onclick=()=>openModal('#leaderModal');$('#addLeader2').onclick=()=>openModal('#leaderModal');$('#quickLeader').onclick=()=>openModal('#leaderModal');$('#addPenalty').onclick=()=>openModal('#penaltyModal');$('#quickPenalty').onclick=()=>openModal('#penaltyModal');$('#refresh').onclick=load;
$$('[data-close]').forEach(b=>b.onclick=()=>closeModal('#'+b.dataset.close));
$('#leaderSearch').oninput=renderLeaders;$('#statusFilter').onchange=renderLeaders;$('#penaltySearch').oninput=renderPenalties;$('#penaltyType').onchange=renderPenalties;
$('#leaderForm').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));await api('/api/leaders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});closeModal('#leaderModal');e.target.reset();load()}catch(err){alert(err.message)}};
$('#penaltyForm').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.amount=Number(d.amount||0);await api('/api/penalties',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});closeModal('#penaltyModal');e.target.reset();load()}catch(err){alert(err.message)}};
async function removeLeader(id){if(!confirm('Удалить лидера и связанные с ним взыскания?'))return;await api('/api/leaders/'+id,{method:'DELETE'});load()}
async function removePenalty(id){if(!confirm('Удалить это взыскание?'))return;await api('/api/penalties/'+id,{method:'DELETE'});load()}
window.removeLeader=removeLeader;window.removePenalty=removePenalty;
load();
